# Site settings (baseurl must end with a trailing slash!)
# Set baseURL from command line
languageCode = "en-us"
title = "Tyler Stapler's Personal Website"
theme = "espouse"
copyright = "Copyright &#169; by Tyler Stapler"

assetDir="themes/espouse/static"
enableEmoji = true
ignoreLogs = ['warning-goldmark-raw-html']
enableGitInfo = false
enableRobotsTXT = true
# The theme uses pagination for post, gallery, and project listings.
[pagination]
pagerSize = 12

# The theme supports disqus, which will appear only on deployed sites,
# not locally when run with `hugo server`; as with standard Hugo disqus,
# you can specify disqus_identifier, disqus_title, and disqus_url in the
# front matter of specific content.
#disqusShortname = "yourDisqusShortname"
pygmentsCodefences = true

[taxonomies]
  topic = "topics"
  tag = "tags"
  technology = "technogies"

[params]
  author = "Tyler Stapler"
  github = "https://github.com/tstapler"
  facebook = "https://facebook.com/staplz"
  og_image = "/images/og.png"
  sitename = "Tyler Stapler's Personal Website"
  twitter = "@TStaplz"

[permalinks]
  posts = "/:year/:month/:title/"

sectionPagesMenu = "main"
[[menu.main]]
name = "Home"
weight = -1
identifier = "/"
url = "/"
pre = "home icon"

[[menu.main]]
name = "Blog"
weight = 10
identifier = "blog"
url = "/blog/"
pre = "book icon"

[[menu.main]]
name = "Projects"
identifier = "projects"
url = "/projects/"
pre = "keyboard icon"
[Params]
gatag="UA-111008601-1"
github_url="https://github.com/tstapler/personal-website"

    #
    # Contains the main grid cell of your site (such as a picture of yourself)
    # along with your name, description, and email. Any empty field will
    # not be included. Not providing an image will use a color. Not specifying
    # the Header results in this cell not appearing in the site.
    #
    [Params.Header]

        # This is optional
        name = "Tyler Stapler"

        # This is optional
        description = "I'm Software Engineer with a desire to create. My interests are Distributed Systems and Security. I'm always searching for opportunities to hone my engineering prowess and solve challenging problems with software. My thirst for knowledge, positivity, and tenacity are all benefits I bring to any team I'm a part of. Check out the rest of my site to see some of my interests and achievements."

        # This is optional
        email = "tystapler@gmail.com"

	# A list of technogies you use, supports the following fields:
	#
	# name, icon_url, and description

    [[Params.Technologies]]
    name = "Python"
    icon_url = "img/tech-logos/python-logo-notext.svg"

    [[Params.Technologies]]
    name = "Go"
    icon_url = "img/tech-logos/gopher.svg"

    [[Params.Technologies]]
    name = "Kubernetes"
    icon_url = "img/tech-logos/kubernetes.svg"

    [[Params.Technologies]]
    name = "Dart"
    icon_url = "img/tech-logos/dart.svg"

    [[Params.Technologies]]
    name = "Native Script"
    icon_url = "img/tech-logos/nativescript.svg"

    [[Params.Technologies]]
    name = "Ruby"
    icon_url = "img/tech-logos/ruby.svg"

    [[Params.Technologies]]
    name = "Ansible"
    icon_url = "img/tech-logos/ansible.svg"

    [[Params.Technologies]]
    name = "Angular 2"
    icon_url = "img/tech-logos/angularjs.svg"

    [[Params.Technologies]]
    name = "Node JS"
    icon_url = "img/tech-logos/nodejs.svg"

    [[Params.Technologies]]
    name = "Typescript"
    icon_url = "img/tech-logos/typescript.svg"

    [[Params.Technologies]]
    name = "Amazon Web Services"
    icon_url = "img/tech-logos/aws.svg"
    # Contains the footer of your main page and will also append items to
    # the end of your sidebar in non-homepage pages.
    #
[Params.Footer]

#
# Represents the list of icons and associated links to use in your
# footer and sidebar. Your copyright information will always be
# shown in the footer.
#
# The icon class is a semantic ui icon classname.
#
#   e.g. twitter == "fa fa-twitter"
#

[[Params.Footer.List]]

    icon_class = "linkedin icon"
    icon_link = "https://www.linkedin.com/in/tstapler"

[[Params.Footer.List]]

    icon_class = "github icon"
    icon_link = "https://github.com/tstapler"
